language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t amranprogramming/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true amranprogramming/docker-react npm run test